create table account (id bigint not null auto_increment, password varchar(255), shipping_address_prefered_for_billing bit not null, username varchar(255), billing_address_id bigint, shipping_address_id bigint, primary key (id));
create table account_roles (account_id bigint not null, roles_id integer not null);
create table address (id bigint not null auto_increment, address1 varchar(255), address2 varchar(255), city varchar(255), country varchar(255), first_name varchar(255), last_name varchar(255), phone varchar(255), postal_code varchar(255), state varchar(255), type varchar(255), primary key (id));
create table category (id integer not null auto_increment, kubik_id integer not null, name varchar(255), root_category bit not null, parent_category_id integer, primary key (id));
create table customer_order (id bigint not null auto_increment, abandoned_date datetime, confirmed_date datetime, error_date datetime, invoice_id bigint, open_date datetime, processed_date datetime, shipping_cost double precision, shipping_method varchar(255), status varchar(255), sub_total double precision, to_confirm_date datetime, total_amount double precision, total_quantity integer not null, total_weight integer, transaction_gateway varchar(255), transaction_id varchar(255), uuid varchar(255), account_id bigint, applicable_shipping_cost_level_id integer, billing_address_id bigint, shipping_address_id bigint, primary key (id));
create table customer_order_detail (id bigint not null auto_increment, quantity_ordered integer not null, quantity_shipped integer not null, total_amount double precision, unit_price double precision, customer_order_id bigint, product_id integer, primary key (id));
create table kubik_notification (id bigint not null auto_increment, action varchar(255), creation_date datetime, error longtext, error_date datetime, kos_id bigint not null, processed_date datetime, status varchar(255), type varchar(255), primary key (id));
create table product (id integer not null auto_increment, author varchar(255), available bit not null, collection varchar(255), date_published datetime, ean13 varchar(255), height integer, isbn varchar(255), kubik_id integer not null, manufacturer varchar(255), price double precision not null, thickness integer, title varchar(255), weight integer, width integer, category_id integer, primary key (id));
create table product_image (id bigint not null auto_increment, content_length bigint not null, size varchar(255), product_id integer, primary key (id));
create table role (id integer not null auto_increment, name varchar(255), type varchar(255), primary key (id));
create table shipping_cost_level (id integer not null auto_increment, cost double precision not null, weight integer, primary key (id));
alter table account add constraint UK_gex1lmaqpg0ir5g1f5eftyaa1 unique (username);
alter table account_roles add constraint UK_mmj6hsswgcj24k77j9viaqy8x unique (roles_id);
alter table customer_order add constraint UK_oaco7klgy94527rk6pwus1tdv unique (uuid);
alter table account add constraint FK_bmf31vx1dll6y6vx2kq1hp9pk foreign key (billing_address_id) references address (id);
alter table account add constraint FK_s7dl68hnrf0x7cp4tkr3llyxh foreign key (shipping_address_id) references address (id);
alter table account_roles add constraint FK_mmj6hsswgcj24k77j9viaqy8x foreign key (roles_id) references role (id);
alter table account_roles add constraint FK_cgiq4c38ilthc7m6260xyynxb foreign key (account_id) references account (id);
alter table category add constraint FK_f82dv7p1qn6jysxl4vadnb4mn foreign key (parent_category_id) references category (id);
alter table customer_order add constraint FK_rnms21agqey5db5ksktf4g5px foreign key (account_id) references account (id);
alter table customer_order add constraint FK_4o75myhdgqsa5o5olrhfeyigd foreign key (applicable_shipping_cost_level_id) references shipping_cost_level (id);
alter table customer_order add constraint FK_2v96w42yvgnxdr3o0y3mxgatt foreign key (billing_address_id) references address (id);
alter table customer_order add constraint FK_o7e9mjk25p536qvy4thrlhh59 foreign key (shipping_address_id) references address (id);
alter table customer_order_detail add constraint FK_ruoo896i8q62t2u6c756cemjg foreign key (customer_order_id) references customer_order (id);
alter table customer_order_detail add constraint FK_ovwqssv6vtsyuehx68g0uelkl foreign key (product_id) references product (id);
alter table product add constraint FK_rlaghtegr0yx2c1q1s6nkqjlh foreign key (category_id) references category (id);
alter table product_image add constraint FK_a8243l5b6mtej47854pwmgbdk foreign key (product_id) references product (id);