FROM java:openjdk-8-alpine

MAINTAINER Daniel Lavoie <dlavoie@cspinformatique.com>

EXPOSE 8060

CMD ["java", "-jar", "/kubik-product-vehicule/kubik-product-vehicule.jar"]

ADD target/kubik-product-vehicule.jar /kubik-product-vehicule/kubik-product-vehicule.jar
